### ISSUE TITLE
Parser crashes by default when parsing Sol in OnFrameStep (unmodified)

### ISSUE THREAD

**Issue by Labreezy** [dantarion/bbtools#9]
I think it's something to do with the way we parse else statements, the crash occurs when parsing the state OnFrameStep.

Error Message:

```
Traceback (most recent call last):
  File "C:\Python27\lib\pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "C:\Python27\lib\pdb.py", line 1233, in _runscript
    self.run(statement)
  File "C:\Python27\lib\bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "gg_rev_script_parser.py", line 1, in <module>
    import os, struct, json, astor, sys
  File "gg_rev_script_parser.py", line 273, in parse_bbscript
    parse_bbscript_routine(f, os.path.getsize(f.name))
  File "gg_rev_script_parser.py", line 184, in parse_bbscript_routine
    astStack.append(ifnode.orelse)
AttributeError: 'Expr' object has no attribute 'orelse'
```

[Zipped script file that causes the crash](https://github.com/dantarion/bbtools/files/1100711/SOL_crash.zip)

**Comment by Labreezy** [comment]
Fixed by changing 15 to the binary operator != (was 16)
